server.port=8080
spring.application.name=ewm-main-service

spring.datasource.url=jdbc:postgresql://localhost:6542/ewm
spring.datasource.username=ewm
spring.datasource.password=ewm

spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always

stat.server.url=http://localhost:9090
